name: Verify DevContainer

on:
  push:
    paths:
      - '.devcontainer/**'
      - '.github/workflows/devcontainer.yml'
  pull_request:
    paths:
      - '.devcontainer/**'

jobs:
  verify-devcontainer:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build devcontainer
      run: |
        cd .devcontainer
        docker build -t seekdeep-dev .
        
    - name: Test basic functionality
      run: |
        docker run --rm seekdeep-dev bash -c "
          gcc --version && 
          g++ --version && 
          cmake --version && 
          python3 --version &&
          echo 'DevContainer build successful!'
        "
